# Auto-generated by refactor script
from senna_ai.telemetry.models import RefLapFile, LapTrace
from senna_ai.track.corner_detection import Corner, CornerTarget
from senna_ai.coaching.coaching_constants import TIER_PROMOTION_LAPS
import logging

log = logging.getLogger(__name__)




class CompositeLap:
    """Builds per-corner progressive targets from multiple reference laps."""

    def __init__(self, corners: list[Corner], ref_laps: list[RefLapFile]):
        self.corners = corners
        self.targets: dict[int, CornerTarget] = {}
        self.track_length = ref_laps[0].track_length if ref_laps else 0.0
        self._fastest_lap_time = min(
            (l.lap_time for l in ref_laps if l.lap_time > 0), default=0.0
        )
        self._build_targets(ref_laps)

    def _build_targets(self, ref_laps: list[RefLapFile]):
        MAX_TIERS = 10
        for corner in self.corners:
            ct = CornerTarget(corner=corner)
            traces_and_speeds = []
            for lap in ref_laps:
                pts = lap.trace.get_corner_slice(corner, margin=50)
                if len(pts) < 5:
                    continue
                trace = LapTrace(points=pts, lap_time=lap.lap_time)
                apex_pt = trace.get_at_dist(corner.apex_m, window=50)
                apex_speed = apex_pt.speed_kph if apex_pt else 0
                if apex_speed > 10:
                    traces_and_speeds.append((trace, apex_speed))
            if not traces_and_speeds:
                ct.target_trace = None
                ct.target_apex_speed = corner.apex_speed_kph
                ct.target_brake_m = corner.brake_point_m
                ct.target_exit_speed = corner.exit_speed_kph
                ct.target_label = "No ref data"
                self.targets[corner.index] = ct
                continue
            traces_and_speeds.sort(key=lambda x: x[1])
            if len(traces_and_speeds) > MAX_TIERS:
                step = len(traces_and_speeds) / MAX_TIERS
                bucketed = []
                for i in range(MAX_TIERS):
                    idx = int(i * step + step / 2)
                    idx = min(idx, len(traces_and_speeds) - 1)
                    bucketed.append(traces_and_speeds[idx])
                traces_and_speeds = bucketed
            ct.available_traces = [t for t, _ in traces_and_speeds]
            ct.available_times = [s for _, s in traces_and_speeds]
            ct.tier = 0
            self._apply_tier(ct)
            self.targets[corner.index] = ct
        log.info("Composite lap: %d corner targets built from %d ref laps, fastest=%.3fs",
                 len(self.targets), len(ref_laps), self._fastest_lap_time)

    def set_player_level(self, corner_idx: int, player_apex_speed: float):
        ct = self.targets.get(corner_idx)
        if not ct or not ct.available_times:
            return
        ct.player_best_apex_speed = max(ct.player_best_apex_speed, player_apex_speed)
        player_tier = 0
        for i, ref_speed in enumerate(ct.available_times):
            if ref_speed > ct.player_best_apex_speed:
                player_tier = i
                break
        else:
            player_tier = len(ct.available_times) - 1
        ct.tier = min(player_tier, len(ct.available_traces) - 1)
        self._apply_tier(ct)

    def _apply_tier(self, ct: CornerTarget):
        if not ct.available_traces:
            return
        idx = min(ct.tier, len(ct.available_traces) - 1)
        ct.target_trace = ct.available_traces[idx]
        apex_pt = ct.target_trace.get_at_dist(ct.corner.apex_m, window=50)
        ct.target_apex_speed = apex_pt.speed_kph if apex_pt else ct.corner.apex_speed_kph
        brake_m = ct.target_trace.find_brake_point(ct.corner, search_range=250)
        ct.target_brake_m = brake_m if brake_m else ct.corner.brake_point_m
        exit_pt = ct.target_trace.get_at_dist(ct.corner.exit_m, window=50)
        ct.target_exit_speed = exit_pt.speed_kph if exit_pt else ct.corner.exit_speed_kph
        total_tiers = len(ct.available_traces)
        ct.target_label = f"Tier {ct.tier + 1}/{total_tiers}"
        log.info(
            "  C%d target: %s | apex=%.0fkph brake@%.0fm exit=%.0fkph (player best=%.0fkph)",
            ct.corner.index, ct.target_label, ct.target_apex_speed,
            ct.target_brake_m, ct.target_exit_speed, ct.player_best_apex_speed,
        )

    def check_promotion(self, corner_idx: int, driver_apex_speed: float) -> bool:
        ct = self.targets.get(corner_idx)
        if not ct:
            return False
        ct.player_best_apex_speed = max(ct.player_best_apex_speed, driver_apex_speed)
        if driver_apex_speed >= ct.target_apex_speed - 2:
            ct.consecutive_beats += 1
            if ct.consecutive_beats >= TIER_PROMOTION_LAPS:
                old_tier = ct.tier
                ct.tier = min(ct.tier + 1, len(ct.available_traces) - 1)
                if ct.tier != old_tier:
                    ct.consecutive_beats = 0
                    self._apply_tier(ct)
                    log.info("🎯 C%d PROMOTED: Tier %d → %d", corner_idx, old_tier + 1, ct.tier + 1)
                    return True
        else:
            ct.consecutive_beats = max(0, ct.consecutive_beats - 1)
        return False

    def get_composite_time_estimate(self) -> float:
        if not self._fastest_lap_time or self._fastest_lap_time <= 0:
            return 0.0
        base_time = self._fastest_lap_time
        speed_ratios = []
        for ct in self.targets.values():
            if ct.target_apex_speed > 10 and ct.corner.apex_speed_kph > 10:
                ratio = ct.corner.apex_speed_kph / ct.target_apex_speed
                speed_ratios.append(ratio)
        if speed_ratios:
            avg_ratio = sum(speed_ratios) / len(speed_ratios)
            return base_time / avg_ratio
        return base_time


# ═══════════════════════════════════════════════════════════════════════════
# TTS Speaker (background thread)
# ═══════════════════════════════════════════════════════════════════════════
