# Auto-generated by refactor script
from senna_ai.track.corner_detection import Corner
from senna_ai.telemetry.models import LapTrace
from dataclasses import dataclass, field
from typing import Optional
import logging
import math

log = logging.getLogger(__name__)

@dataclass
class Complex:
    index: int
    name: str
    corner_indices: list[int]
    corners: list[Corner]
    start_m: float
    end_m: float
    complex_type: str = ""                            # esses / chicane / double_apex / linked / flow_zone
    n_direction_changes: int = 0
    flow_zone: Optional[tuple[float, float]] = None
    # Enhanced metrics for high_speed_flow complexes
    steering_rms: float = 0.0                          # Root mean square of steering magnitude
    min_speed_delta_kph: float = 0.0                   # Minimum speed drop across complex
    exit_speed_delta_kph: float = 0.0                  # Exit speed loss of final corner
    avg_speed_kph: float = 0.0                         # Average speed through complex


def _build_dist_index(trace: LapTrace) -> tuple[list[float], list]:
    """Pre-sort points by distance for O(log N) lookups."""
    pts = sorted(trace.points, key=lambda p: p.dist_m)
    dists = [p.dist_m for p in pts]
    return dists, pts


def _get_at_dist_fast(dists: list[float], pts: list, dist_m: float,
                      window: float = 10.0):
    """Bisect-based O(log N) nearest-point lookup."""
    from bisect import bisect_left
    idx = bisect_left(dists, dist_m)
    best = None
    best_d = window
    for j in range(max(0, idx - 1), min(len(dists), idx + 2)):
        d = abs(dists[j] - dist_m)
        if d < best_d:
            best = pts[j]
            best_d = d
    return best


def _detect_steering_flow_zones(traces: list[LapTrace],
                                steer_thresh: float = 5.0,
                                min_zone_len_m: float = 100.0) -> list[tuple[float, float, int, float]]:
    """Detect zones of continuous steering activity across multiple traces.

    Returns list of (start_m, end_m, n_direction_changes, avg_speed_kph).

    Uses bisect-indexed lookups — O(N log N) instead of O(N²).
    """
    if not traces:
        return []

    ref = traces[0]
    if not ref.points:
        return []

    # Pre-build distance indices for all traces
    indices = [_build_dist_index(t) for t in traces]
    majority = len(traces) / 2

    # For each point in reference, vote on steering activity
    active: list[tuple[float, float, bool]] = []
    for p in ref.points:
        votes = 0
        for dists, pts in indices:
            tp = _get_at_dist_fast(dists, pts, p.dist_m)
            if tp and abs(tp.steer_pct) > steer_thresh:
                votes += 1
        active.append((p.dist_m, p.speed_kph, votes >= majority))

    # Extract contiguous active zones
    zones: list[tuple[float, float, float]] = []
    zone_start = None
    speeds: list[float] = []
    for dist, spd, is_active in active:
        if is_active:
            if zone_start is None:
                zone_start = dist
                speeds = []
            speeds.append(spd)
        else:
            if zone_start is not None and dist - zone_start >= min_zone_len_m:
                zones.append((zone_start, dist, sum(speeds) / len(speeds) if speeds else 0))
            zone_start = None

    if zone_start is not None:
        end_d = active[-1][0]
        if end_d - zone_start >= min_zone_len_m:
            zones.append((zone_start, end_d, sum(speeds) / len(speeds) if speeds else 0))

    # Count direction changes in each zone (per-trace, take max)
    results = []
    for z_start, z_end, avg_spd in zones:
        max_changes = 0
        for dists, pts in indices:
            from bisect import bisect_left, bisect_right
            lo = bisect_left(dists, z_start)
            hi = bisect_right(dists, z_end)
            zone_pts = pts[lo:hi]
            signs = [1 if p.steer_pct > steer_thresh else (-1 if p.steer_pct < -steer_thresh else 0)
                     for p in zone_pts]
            changes = sum(1 for j in range(1, len(signs))
                          if signs[j] != 0 and signs[j - 1] != 0 and signs[j] != signs[j - 1])
            max_changes = max(max_changes, changes)
        results.append((z_start, z_end, max_changes, avg_spd))

    return results


def _detect_driver_reset(trace: LapTrace, start_m: float, end_m: float) -> bool:
    """Detect if driver resets between corners (full throttle, minimal steering).
    
    Returns True if a reset is detected (corners should NOT be merged).
    A reset is detected when ALL of the following occur between start_m and end_m:
    1. Sustained throttle > 85% for at least 0.8 seconds
    2. Steering magnitude RMS < 1.5% for at least 0.5 seconds
    3. Brake = 0 during that window
    4. Lateral G below low-load threshold (0.3g)
    """
    # Get points in the reset window
    reset_points = [p for p in trace.points if start_m <= p.dist_m <= end_m]
    if len(reset_points) < 10:  # Need enough points for meaningful analysis
        return False
    
    # Estimate time between points (assuming ~60Hz telemetry)
    avg_time_gap = 1.0 / 60.0  # ~16.7ms per point
    
    # Check for sustained throttle > 85%
    throttle_threshold = 85.0
    throttle_duration_needed = 0.8  # seconds
    min_throttle_points = int(throttle_duration_needed / avg_time_gap)
    
    # Check for sustained low steering RMS < 1.5%
    steering_threshold = 1.5
    steering_duration_needed = 0.5  # seconds
    min_steering_points = int(steering_duration_needed / avg_time_gap)
    
    # Lateral G threshold (low-load)
    lateral_g_threshold = 0.3  # 0.3g
    
    # Find windows where all conditions are met
    for i in range(len(reset_points) - min_throttle_points + 1):
        window = reset_points[i:i + min_throttle_points]
        
        # Check throttle condition
        throttle_ok = all(p.throttle_pct > throttle_threshold for p in window)
        if not throttle_ok:
            continue
            
        # Check brake condition (must be 0)
        brake_ok = all(p.brake_pct == 0 for p in window)
        if not brake_ok:
            continue
            
        # Check for low steering within this throttle window
        # We need at least min_steering_points consecutive points with low steering
        for j in range(len(window) - min_steering_points + 1):
            steering_window = window[j:j + min_steering_points]
            
            # Calculate steering RMS
            steering_squares = [p.steer_pct * p.steer_pct for p in steering_window]
            steering_rms = math.sqrt(sum(steering_squares) / len(steering_squares))
            
            if steering_rms < steering_threshold:
                # Check lateral G (estimated from steering and speed)
                # Simple estimation: lateral G ≈ (steer_pct/100) * (speed_kph/100) * 0.5
                # This is a rough approximation - in real implementation you'd use proper physics
                lateral_g_ok = True
                for p in steering_window:
                    # Very rough lateral G estimation
                    estimated_lateral_g = abs(p.steer_pct / 100.0) * (p.speed_kph / 100.0) * 0.5
                    if estimated_lateral_g > lateral_g_threshold:
                        lateral_g_ok = False
                        break
                
                if lateral_g_ok:
                    log.debug("Driver reset detected between %.0fm and %.0fm: throttle=%.0f%%, steering_rms=%.2f%%, brake=0, lateral_g<%.1fg",
                             start_m, end_m, throttle_threshold, steering_rms, lateral_g_threshold)
                    return True
    
    return False


def _compute_complex_metrics(cx: Complex, ref_traces: list[LapTrace]) -> None:
    """
    Compute enhanced metrics for complex analysis.
    
    For high_speed_flow complexes, computes:
    - Steering RMS within the complex
    - Steering direction change count
    - Minimum speed delta across entire complex
    - Exit speed delta of final corner
    """
    if not ref_traces:
        return
    
    # Use the fastest reference trace for metrics
    fastest_trace = min(ref_traces, key=lambda t: t.lap_time) if ref_traces[0].lap_time > 0 else ref_traces[0]
    
    # Get points within complex zone
    zone_points = [p for p in fastest_trace.points 
                   if cx.start_m <= p.dist_m <= cx.end_m]
    
    if len(zone_points) < 10:
        return
    
    # Compute steering RMS
    steering_squares = [p.steer_pct * p.steer_pct for p in zone_points]
    cx.steering_rms = math.sqrt(sum(steering_squares) / len(steering_squares))
    
    # Compute steering direction changes
    steer_thresh = 2.0  # Lower threshold for high-speed flow detection
    signs = [1 if p.steer_pct > steer_thresh else 
             (-1 if p.steer_pct < -steer_thresh else 0)
             for p in zone_points]
    
    direction_changes = 0
    for j in range(1, len(signs)):
        if signs[j] != 0 and signs[j-1] != 0 and signs[j] != signs[j-1]:
            direction_changes += 1
    
    cx.n_direction_changes = direction_changes
    
    # Compute speed metrics
    speeds = [p.speed_kph for p in zone_points]
    cx.avg_speed_kph = sum(speeds) / len(speeds)
    
    # Minimum speed delta (entry speed - minimum speed in complex)
    entry_speed = zone_points[0].speed_kph if zone_points else 0
    min_speed = min(speeds)
    cx.min_speed_delta_kph = entry_speed - min_speed
    
    # Exit speed delta (reference exit speed - actual exit speed)
    # For now, use the last corner's exit speed vs complex exit speed
    if cx.corners:
        last_corner = cx.corners[-1]
        exit_point = fastest_trace.get_at_dist(last_corner.exit_m, window=20)
        if exit_point:
            cx.exit_speed_delta_kph = last_corner.exit_speed_kph - exit_point.speed_kph
    
    log.debug("Complex %d metrics: steering_rms=%.2f%%, dir_changes=%d, avg_speed=%.0fkph, min_delta=%.0fkph, exit_delta=%.0fkph",
              cx.index, cx.steering_rms, cx.n_direction_changes, cx.avg_speed_kph,
              cx.min_speed_delta_kph, cx.exit_speed_delta_kph)


def detect_complexes(corners: list[Corner], ref_traces: list[LapTrace] = None) -> list[Complex]:
    """Auto-detect corner complexes from geometry and telemetry."""
    if len(corners) < 2:
        return []

    merge_pairs: set[tuple[int, int]] = set()

    # Method A: Corner proximity + steering continuity
    for i in range(len(corners) - 1):
        c1, c2 = corners[i], corners[i + 1]
        apex_gap = c2.apex_m - c1.apex_m
        exit_to_brake = c2.brake_point_m - c1.exit_m

        log.debug("Complex check C%d→C%d: apex_gap=%.0fm exit_to_brake=%.0fm",
                  c1.index, c2.index, apex_gap, exit_to_brake)

        # Skip if apexes are very far apart — can't be a complex
        if apex_gap > 800:
            continue

        # Check 1: Very close corners always merge
        if exit_to_brake < 80:
            merge_pairs.add((i, i + 1))
            continue

        # Check 2: For corners within 700m apex gap, check steering continuity
        # Key fix: check steering BEFORE rejecting on distance
        if apex_gap < 700 and ref_traces:
            # NEW: First check for driver reset between corners
            reset_detected = False
            for trace in ref_traces[:5]:
                if _detect_driver_reset(trace, c1.exit_m, c2.brake_point_m):
                    reset_detected = True
                    log.debug("Reset detected between C%d and C%d - NOT merging", c1.index, c2.index)
                    break
            
            if reset_detected:
                # Driver reset detected - do NOT merge these corners
                continue
            
            # Original steering continuity check (only if no reset detected)
            steer_continuous = False
            for trace in ref_traces[:5]:
                between = [p for p in trace.points
                           if c1.apex_m <= p.dist_m <= c2.apex_m]
                if len(between) >= 3:
                    # Adaptive threshold: lower for high-speed sections
                    avg_spd = sum(p.speed_kph for p in between) / len(between)
                    steer_thresh = 2.0 if avg_spd > 120 else 3.0

                    min_steer = min(abs(p.steer_pct) for p in between)
                    signs = [1 if p.steer_pct > steer_thresh else
                             (-1 if p.steer_pct < -steer_thresh else 0)
                             for p in between]
                    sign_changes = sum(1 for j in range(1, len(signs))
                                       if signs[j] != 0 and signs[j-1] != 0
                                       and signs[j] != signs[j-1])
                    if min_steer > steer_thresh or sign_changes >= 2:
                        steer_continuous = True
                        break
            if steer_continuous:
                merge_pairs.add((i, i + 1))
                continue

        # Check 3: Relaxed proximity for consensus corners
        # Consensus median exit/brake compress gaps, so use apex gap
        if apex_gap < 500 and exit_to_brake < 400:
            merge_pairs.add((i, i + 1))

    # Method B: Steering flow detection
    single_corner_flows: list[tuple] = []
    if ref_traces:
        flow_zones = _detect_steering_flow_zones(ref_traces[:5])
        for zone_start, zone_end, n_changes, avg_speed_zone in flow_zones:
            zone_corners = []
            for i, c in enumerate(corners):
                if (c.brake_point_m < zone_end + 100 and c.exit_m > zone_start - 100):
                    zone_corners.append(i)
            if len(zone_corners) >= 2:
                for j in range(len(zone_corners) - 1):
                    pair = (zone_corners[j], zone_corners[j + 1])
                    if pair not in merge_pairs:
                        merge_pairs.add(pair)
            elif len(zone_corners) == 1 and n_changes >= 3:
                single_corner_flows.append(
                    (zone_corners[0], zone_start, zone_end, n_changes, avg_speed_zone))

    groups: list[list[int]] = []
    for i, j in sorted(merge_pairs):
        merged = False
        for group in groups:
            if i in group or j in group:
                if i not in group: group.append(i)
                if j not in group: group.append(j)
                merged = True
                break
        if not merged:
            groups.append([i, j])

    complexes = []
    for k, group in enumerate(groups):
        indices = sorted(set(group))
        ccorners = [corners[i] for i in indices]
        cidx = [corners[i].index for i in indices]
        speeds = [c.apex_speed_kph for c in ccorners]
        avg_speed = sum(speeds) / len(speeds) if speeds else 0
        if avg_speed > 150:
            ctype = "esses"
        elif avg_speed < 80 and len(ccorners) <= 3:
            ctype = "chicane"
        elif len(ccorners) == 2 and abs(ccorners[0].apex_gear - ccorners[1].apex_gear) <= 1:
            ctype = "double_apex"
        else:
            ctype = "linked"
        name = f"Complex {k+1} (C{'–C'.join(str(i) for i in cidx)})"
        cx = Complex(index=k+1, name=name, corner_indices=cidx, corners=ccorners,
                     start_m=ccorners[0].brake_point_m, end_m=ccorners[-1].exit_m,
                     complex_type=ctype)
        # Compute enhanced metrics for the complex
        if ref_traces:
            _compute_complex_metrics(cx, ref_traces)
        complexes.append(cx)

    next_idx = len(complexes) + 1
    for ci, z_start, z_end, n_changes, avg_speed in single_corner_flows:
        c = corners[ci]
        already_in = any(c.index in cx.corner_indices for cx in complexes)
        if already_in:
            continue
        if avg_speed > 140:
            ctype = "esses"
        elif avg_speed < 80:
            ctype = "chicane"
        else:
            ctype = "flow_zone"
        name = f"Complex {next_idx} (C{c.index} flow)"
        cx = Complex(index=next_idx, name=name, corner_indices=[c.index],
                     corners=[c], start_m=z_start, end_m=z_end,
                     complex_type=ctype, n_direction_changes=n_changes,
                     flow_zone=(z_start, z_end))
        # Compute enhanced metrics for the complex
        if ref_traces:
            _compute_complex_metrics(cx, ref_traces)
        complexes.append(cx)
        next_idx += 1

    log.info("Complex detection: %d complexes found from %d corners", len(complexes), len(corners))
    for cx in complexes:
        log.info("  %s [%s] %.0fm–%.0fm", cx.name, cx.complex_type, cx.start_m, cx.end_m)

    return complexes
