# Auto-generated by refactor script
from senna_ai.track.corner_detection import Corner
from senna_ai.telemetry.models import LapTrace
from senna_ai.track.track_model import CornerStats
from dataclasses import dataclass
from typing import Optional


@dataclass
class ForceStageScores:
    current_stage: int = 0
    s1_brake: float = 0.0
    s2_load: float = 0.0
    s3_rotation: float = 0.0
    s4_blending: float = 0.0
    # Actual computed scores used by engine
    s1_longitudinal: float = 0.0
    s2_lateral: float = 0.0
    stage_progress: float = 0.0




class ForceStageModel:
    """Force Stage technique model: technique-first coaching."""
    S1_PASS = 0.65
    S2_PASS = 0.60
    S3_PASS = 0.55

    def __init__(self):
        self.scores: dict[int, ForceStageScores] = {}
        self.mode = "COMPARISON"

    def score_corner(self, corner: Corner, driver_trace: LapTrace,
                     corner_stats: Optional[CornerStats] = None) -> ForceStageScores:
        fs = ForceStageScores()
        pts = driver_trace.points
        if len(pts) < 10:
            return fs

        brake_zone = [p for p in pts
                      if corner.brake_point_m - 10 <= p.dist_m <= corner.apex_m]
        if brake_zone:
            decels = []
            for i in range(1, len(brake_zone)):
                dt_dist = brake_zone[i].dist_m - brake_zone[i-1].dist_m
                if dt_dist > 0.5:
                    dv = brake_zone[i-1].speed_kph - brake_zone[i].speed_kph
                    avg_v = (brake_zone[i].speed_kph + brake_zone[i-1].speed_kph) / 2 / 3.6 + 0.1
                    decel_g = (dv / 3.6) / (dt_dist / avg_v) / 9.81
                    decels.append(abs(decel_g))
            peak_decel = max(decels) if decels else 0
            peak_brake = max(p.brake_pct for p in brake_zone)
            ramp_pts = [p for p in brake_zone if p.brake_pct > 5]
            if len(ramp_pts) >= 2:
                peak_idx = max(range(len(ramp_pts)), key=lambda i: ramp_pts[i].brake_pct)
                ramp_to_peak = ramp_pts[peak_idx].dist_m - ramp_pts[0].dist_m
                commitment = min(1.0, 20.0 / (ramp_to_peak + 1))
            else:
                commitment = 0.3
            decel_score = min(1.0, peak_decel / 2.5)
            brake_score = min(1.0, peak_brake / 85)
            fs.s1_longitudinal = decel_score * 0.4 + brake_score * 0.3 + commitment * 0.3

        corner_zone = [p for p in pts
                       if corner.brake_point_m <= p.dist_m <= corner.exit_m]
        if corner_zone:
            max_steer = max(abs(p.steer_pct) for p in corner_zone)
            drv_apex = driver_trace.get_at_dist(corner.apex_m, window=30)
            if drv_apex and corner_stats and corner_stats.apex_mean > 0:
                lateral_score = min(1.0, drv_apex.speed_kph / corner_stats.apex_mean)
            elif drv_apex:
                lateral_score = min(1.0, drv_apex.speed_kph / max(corner.apex_speed_kph, 30))
            else:
                lateral_score = 0.3
            steer_usage = min(1.0, max_steer / 60)
            fs.s2_lateral = lateral_score * 0.7 + steer_usage * 0.3

        trail_pts = [p for p in pts
                     if corner.brake_point_m <= p.dist_m <= corner.apex_m + 20]
        if trail_pts:
            overlap_count = sum(1 for p in trail_pts
                               if p.brake_pct > 3 and abs(p.steer_pct) > 3)
            overlap_ratio = overlap_count / len(trail_pts)
            coast_count = sum(1 for p in trail_pts
                             if p.brake_pct < 3 and p.throttle_pct < 10)
            coast_ratio = coast_count / len(trail_pts)
            brake_vals = [p.brake_pct for p in trail_pts if p.brake_pct > 2]
            if len(brake_vals) >= 3:
                taper_zone = brake_vals[len(brake_vals)*3//4:]
                if len(taper_zone) >= 2:
                    diffs = [abs(taper_zone[i] - taper_zone[i-1]) for i in range(1, len(taper_zone))]
                    smoothness = 1.0 - min(1.0, max(diffs) / 30)
                else:
                    smoothness = 0.5
            else:
                smoothness = 0.3
            fs.s3_rotation = min(1.0, overlap_ratio * 0.5 + (1 - coast_ratio) * 0.3 + smoothness * 0.2)

        blend_pts = [p for p in pts if corner.brake_point_m <= p.dist_m <= corner.exit_m]
        if blend_pts:
            multi_force = sum(1 for p in blend_pts
                             if (p.brake_pct > 3 or p.throttle_pct > 10) and abs(p.steer_pct) > 5)
            blend_ratio = multi_force / len(blend_pts)
            speeds = [p.speed_kph for p in blend_pts]
            if len(speeds) >= 5:
                diffs = [abs(speeds[i] - speeds[i-1]) for i in range(1, len(speeds))]
                avg_diff = sum(diffs) / len(diffs)
                smoothness = 1.0 - min(1.0, avg_diff / 8)
            else:
                smoothness = 0.5
            fs.s4_blending = blend_ratio * 0.6 + smoothness * 0.4

        if fs.s1_longitudinal < self.S1_PASS:
            fs.current_stage = 1
            fs.stage_progress = fs.s1_longitudinal / self.S1_PASS
        elif fs.s2_lateral < self.S2_PASS:
            fs.current_stage = 2
            fs.stage_progress = fs.s2_lateral / self.S2_PASS
        elif fs.s3_rotation < self.S3_PASS:
            fs.current_stage = 3
            fs.stage_progress = fs.s3_rotation / self.S3_PASS
        else:
            fs.current_stage = 4
            fs.stage_progress = fs.s4_blending

        self.scores[corner.index] = fs
        return fs

    def get_technique_instruction(self, corner: Corner, fs: ForceStageScores) -> Optional[str]:
        prefix = f"Corner {corner.index}."
        if fs.current_stage == 1 and fs.s1_longitudinal < self.S1_PASS:
            if fs.s1_longitudinal < 0.3:
                return f"{prefix} Test your braking. Hit the pedal harder in a straight line before turn-in."
            return f"{prefix} Good commitment. Push 10 percent harder to find peak deceleration."
        if fs.current_stage == 2 and fs.s2_lateral < self.S2_PASS:
            if fs.s2_lateral < 0.4:
                return f"{prefix} Carry more speed mid-corner. Trust the lateral grip."
            return f"{prefix} Close to the lateral limit. Push the entry speed a touch."
        if fs.current_stage == 3 and fs.s3_rotation < self.S3_PASS:
            if fs.s3_rotation < 0.3:
                return f"{prefix} You're off brake before turn-in. Trail 5 to 10 percent into the turn."
            elif fs.s3_rotation < 0.5:
                return f"{prefix} Trail braking developing. Hold it a touch longer through turn-in."
            return f"{prefix} Good trail brake. Smooth the release. Let it taper."
        if fs.current_stage == 4 and fs.s4_blending < 0.6:
            if fs.s4_blending < 0.4:
                return f"{prefix} Blend the forces. Brake tapers as steering increases."
            return f"{prefix} Getting smoother. Keep forces overlapping through the transition."
        return None


