# -*- coding: utf-8 -*-
# Auto-generated by refactor script
from senna_ai.track.corner_detection import Corner, Sector
from senna_ai.telemetry.models import LapTrace, RefLapFile
from senna_ai.coaching.coaching_constants import BRAKE_THRESHOLD
from dataclasses import dataclass, field
from typing import Optional
import logging

log = logging.getLogger(__name__)


@dataclass
class CornerStats:
    brake_points: list[float] = field(default_factory=list)
    apex_speeds: list[float] = field(default_factory=list)
    exit_speeds: list[float] = field(default_factory=list)
    peak_brake_pcts: list[float] = field(default_factory=list)
    brake_duration_m: list[float] = field(default_factory=list)
    # Computed stats (populated by TrackModel._build)
    brake_mean: float = 0.0
    brake_std: float = 0.0
    brake_p10: float = 0.0
    brake_p90: float = 0.0
    apex_mean: float = 0.0
    apex_std: float = 0.0
    apex_p90: float = 0.0
    exit_mean: float = 0.0
    exit_p90: float = 0.0
    peak_brake_mean: float = 0.0
    brake_duration_mean: float = 0.0
    straight_after_m: float = 0.0
    importance: float = 1.0



class TrackModel:
    """Statistical model of a track built from ALL reference laps."""

    def __init__(self, corners: list[Corner], sectors: list[Sector],
                 ref_laps: list['RefLapFile'], track_length: float = 0):
        self.corner_stats: dict[int, CornerStats] = {}
        self.track_length = track_length
        self._build(corners, sectors, ref_laps)

    def _build(self, corners: list[Corner], sectors: list[Sector],
               ref_laps: list['RefLapFile']):
        import statistics as stat

        for corner in corners:
            cs = CornerStats()

            for lap in ref_laps:
                pts = lap.trace.get_corner_slice(corner, margin=80)
                if len(pts) < 5:
                    continue
                trace = LapTrace(points=pts)

                bp = trace.find_brake_point(corner, search_range=250)
                if bp:
                    cs.brake_points.append(bp)

                apex_pt = trace.get_at_dist(corner.apex_m, window=50)
                if apex_pt and apex_pt.speed_kph > 10:
                    cs.apex_speeds.append(apex_pt.speed_kph)

                exit_pt = trace.get_at_dist(corner.exit_m, window=50)
                if exit_pt and exit_pt.speed_kph > 10:
                    cs.exit_speeds.append(exit_pt.speed_kph)

                zone_brakes = [p.brake_pct for p in pts
                               if corner.brake_point_m - 20 <= p.dist_m <= corner.apex_m]
                if zone_brakes:
                    cs.peak_brake_pcts.append(max(zone_brakes))

                brake_start = None
                brake_end = None
                for p in pts:
                    if p.brake_pct > BRAKE_THRESHOLD and brake_start is None:
                        brake_start = p.dist_m
                    if brake_start and p.brake_pct < 5:
                        brake_end = p.dist_m
                        break
                if brake_start and brake_end:
                    cs.brake_duration_m.append(brake_end - brake_start)

            if cs.brake_points:
                cs.brake_mean = stat.mean(cs.brake_points)
                cs.brake_std = stat.stdev(cs.brake_points) if len(cs.brake_points) > 1 else 0
                sorted_bp = sorted(cs.brake_points)
                cs.brake_p10 = sorted_bp[max(0, int(len(sorted_bp) * 0.9))]
                cs.brake_p90 = sorted_bp[max(0, int(len(sorted_bp) * 0.1))]

            if cs.apex_speeds:
                cs.apex_mean = stat.mean(cs.apex_speeds)
                cs.apex_std = stat.stdev(cs.apex_speeds) if len(cs.apex_speeds) > 1 else 0
                sorted_as = sorted(cs.apex_speeds)
                cs.apex_p90 = sorted_as[max(0, int(len(sorted_as) * 0.9))]

            if cs.exit_speeds:
                cs.exit_mean = stat.mean(cs.exit_speeds)
                sorted_es = sorted(cs.exit_speeds)
                cs.exit_p90 = sorted_es[max(0, int(len(sorted_es) * 0.9))]

            if cs.peak_brake_pcts:
                cs.peak_brake_mean = stat.mean(cs.peak_brake_pcts)

            if cs.brake_duration_m:
                cs.brake_duration_mean = stat.mean(cs.brake_duration_m)

            self.corner_stats[corner.index] = cs

        for sector in sectors:
            cs = self.corner_stats.get(sector.index)
            if not cs:
                continue
            cs.straight_after_m = sector.length_m
            if cs.exit_mean > 30:
                v_mps = cs.exit_mean / 3.6
                v_plus = (cs.exit_mean + 5) / 3.6
                dt = sector.length_m / v_mps - sector.length_m / v_plus
                cs.importance = max(0.5, dt)
            else:
                cs.importance = 1.0

        importances = [cs.importance for cs in self.corner_stats.values()]
        if importances:
            avg_imp = sum(importances) / len(importances)
            if avg_imp > 0:
                for cs in self.corner_stats.values():
                    cs.importance /= avg_imp

        for idx, cs in sorted(self.corner_stats.items()):
            log.info(
                "  TrackModel C%d: brake=%.0f±%.0fm (p10=%.0f p90=%.0f) "
                "apex=%.0f±%.0fkph (p90=%.0f) exit=%.0fkph importance=%.2f",
                idx, cs.brake_mean, cs.brake_std, cs.brake_p10, cs.brake_p90,
                cs.apex_mean, cs.apex_std, cs.apex_p90, cs.exit_mean, cs.importance,
            )

    def get_player_percentile(self, corner_idx: int,
                               brake_m: Optional[float] = None,
                               apex_kph: Optional[float] = None,
                               exit_kph: Optional[float] = None) -> dict[str, float]:
        cs = self.corner_stats.get(corner_idx)
        if not cs:
            return {}
        result = {}
        if brake_m is not None and cs.brake_points:
            later_count = sum(1 for bp in cs.brake_points if bp >= brake_m)
            result["brake"] = (1 - later_count / len(cs.brake_points)) * 100
        if apex_kph is not None and cs.apex_speeds:
            slower_count = sum(1 for s in cs.apex_speeds if s <= apex_kph)
            result["apex"] = slower_count / len(cs.apex_speeds) * 100
        if exit_kph is not None and cs.exit_speeds:
            slower_count = sum(1 for s in cs.exit_speeds if s <= exit_kph)
            result["exit"] = slower_count / len(cs.exit_speeds) * 100
        return result

    def get_brake_profile_analysis(self, corner: Corner,
                                    driver_trace: 'LapTrace') -> dict:
        cs = self.corner_stats.get(corner.index)
        if not cs:
            return {}
        zone_points = [p for p in driver_trace.points
                       if corner.brake_point_m - 10 <= p.dist_m <= corner.apex_m + 20
                       and p.brake_pct > 2]
        if len(zone_points) < 5:
            return {}
        pressures = [p.brake_pct for p in zone_points]
        peak = max(pressures)
        stab_count = 0
        for i in range(1, len(pressures)):
            if abs(pressures[i] - pressures[i - 1]) > 15:
                stab_count += 1
        diffs = [abs(pressures[i] - pressures[i - 1]) for i in range(1, len(pressures))]
        modulation = sum(diffs) / len(diffs) if diffs else 0
        brake_start = zone_points[0].dist_m
        brake_end = zone_points[-1].dist_m
        duration_m = brake_end - brake_start
        result = {
            "peak_pct": peak,
            "peak_vs_mean": peak - cs.peak_brake_mean if cs.peak_brake_mean > 0 else 0,
            "stab_count": stab_count,
            "modulation": modulation,
            "duration_m": duration_m,
            "duration_vs_mean": duration_m - cs.brake_duration_mean if cs.brake_duration_mean > 0 else 0,
            "is_stabbing": stab_count > 3,
            "is_too_hard": peak > cs.peak_brake_mean + 15 if cs.peak_brake_mean > 0 else False,
            "is_too_soft": peak < cs.peak_brake_mean - 15 if cs.peak_brake_mean > 0 else False,
        }
        return result


