# Auto-generated by refactor script



class EnhancedCoachingGenerator:
    """
    Provides varied phrases, complex awareness, and How-To formula.
    """
    
    def __init__(self):
        self.coaching_history = {}  # Track what we've said
        self._init_phrases()
    
    def _init_phrases(self):
        """5 variations for each message type."""
        self.phrases = {
            'brake_early_pre': [
                "Corner {idx}: brake {delta:.0f}m later. Look further ahead, squeeze don't stamp.",
                "C{idx}: you're braking early. Move your marker {delta:.0f}m later.",
                "Into {idx}, brake {delta:.0f}m later than you think. Trust the car.",
                "Corner {idx} approaching: brake point {delta:.0f}m too early. Later marker, commit.",
                "C{idx}: early brakes. Pick a later board, squeeze progressively."
            ],
            'brake_early_post': [
                "C{idx}: braked {delta:.0f}m early. Next lap, later marker, commit.",
                "Early at {idx}. Move it back {delta:.0f}m next time.",
                "{idx}: {delta:.0f}m early on brakes. Later point, smoother squeeze.",
                "Lost time at {idx} entry. Brake {delta:.0f}m later next lap.",
                "C{idx} early. Trust the brakes more next time."
            ],
            'apex_slow_pre': [
                "C{idx}: losing {delta:.0f}kph at apex. Turn in 5m later, clip the inside.",
                "Corner {idx}: slow through apex. Later entry, carry more speed.",
                "Through {idx}, you're {delta:.0f}kph slow. Late apex = fast exit.",
                "C{idx} apex: {delta:.0f}kph down. Delay turn-in, trust the grip.",
                "Into {idx}: late apex needed. Sacrifice entry for exit speed."
            ],
            'apex_slow_post': [
                "C{idx}: {delta:.0f}kph slow apex. Later turn-in next lap.",
                "Slow at {idx} apex. Turn in later, carry more.",
                "{idx} apex: {delta:.0f}kph down. Delay entry next time.",
                "Lost apex speed at {idx}. Later turn-in = more exit speed.",
                "C{idx} apex slow. Trust the lateral grip more."
            ],
            'exit_slow_pre': [
                "C{idx}: losing {delta:.0f}kph on exit. Apex first, then power.",
                "Corner {idx} exit: {delta:.0f}kph down. Get straight earlier.",
                "Through {idx}, you're slow on exit. Nail the apex, power follows.",
                "C{idx}: exit loss. Focus on apex, then squeeze throttle.",
                "Into {idx}: exit speed critical. Perfect apex = early power."
            ],
            'exit_slow_post': [
                "C{idx} exit: lost {delta:.0f}kph. Fix the apex next lap.",
                "Slow exit at {idx}. Apex was the problem.",
                "{idx}: {delta:.0f}kph lost on exit. Earlier apex next time.",
                "Exit loss at {idx}. Apex first, then power.",
                "C{idx} exit slow. Hit the apex perfectly next lap."
            ],
            'no_trail_brake_pre': [
                "C{idx}: need trail brake. Keep 20% brake into the turn.",
                "Corner {idx}: don't dump the brake. Trail it through entry.",
                "Into {idx}: brake while turning. 20% at turn-in.",
                "C{idx}: cliff release. Trail brake into the corner.",
                "Corner {idx}: smooth brake release. Keep pressure past turn-in."
            ],
            'no_trail_brake_post': [
                "C{idx}: no trail brake. Next lap, keep foot on pedal while turning.",
                "Dumped brake at {idx}. Trail next time.",
                "{idx}: cliff release. Brake into the corner next lap.",
                "Lost rotation at {idx}. Trail brake will fix it.",
                "C{idx}: brake release too fast. Trail it next time."
            ],
            'brake_stab_pre': [
                "C{idx}: stabbing brakes. One smooth squeeze, hold, release.",
                "Corner {idx}: pumping the brakes. Squeeze once, hold it.",
                "Into {idx}: too much modulation. One firm squeeze.",
                "C{idx}: brake stabbing. Smooth is fast.",
                "Corner {idx}: brake once, not multiple times."
            ],
            'brake_stab_post': [
                "C{idx}: brake stabbing. One squeeze next time.",
                "Too much modulation at {idx}. Smooth application.",
                "{idx}: pumped the brakes. One firm squeeze next lap.",
                "Brake stabbing at {idx}. Trust one application.",
                "C{idx}: smooth it out next time."
            ],
            'complex_min_speed_pre': [
                "Through {name} (C{corners}): losing {value:.0f}kph. Brake ONCE, then flow.",
                "{name} ahead: one brake zone only. Carry momentum.",
                "In the {name}: brake early ONCE, then steer. Don't touch brakes again.",
                "{name}: {value:.0f}kph slow. One brake, trust the flow.",
                "Through {name}: momentum is key. Brake once, steer twice."
            ],
            'complex_min_speed_post': [
                "{name}: {value:.0f}kph slow. Braked twice—they braked once.",
                "Lost {value:.0f}kph in {name}. One brake next time.",
                "{name}: too many brakes. One zone only.",
                "Through {name}: you braked twice. They braked once.",
                "{name} speed loss: one brake zone next lap."
            ],
            'complex_exit_speed_pre': [
                "{name} exit: losing {value:.0f}kph. Focus on last corner apex.",
                "Through {name}: exit speed critical. Nail the final corner.",
                "{name}: sacrifice entry, nail the exit.",
                "Exit speed low in {name}. Last corner apex is everything.",
                "{name}: {value:.0f}kph lost. Perfect the final apex."
            ],
            'complex_exit_speed_post': [
                "{name} exit: {value:.0f}kph down. Last corner apex next time.",
                "Lost exit speed in {name}. Focus on final corner.",
                "{name}: {value:.0f}kph lost. Nail the last apex.",
                "Exit loss in {name}. Last corner was the problem.",
                "{name} exit slow. Perfect that final corner."
            ]
        }
    
    def _get_key(self, corner_idx, issue_type, pre=True):
        """Get unique key for history tracking."""
        return f"{corner_idx}_{issue_type}_{'pre' if pre else 'post'}"
    
    def generate_pre(self, corner_idx, issue_type, delta=0, value=0, 
                     complex_name="", corners=""):
        """Generate pre-corner advice with 5 variations."""
        key = f"{issue_type}_pre"
        if key not in self.phrases:
            return None
            
        history_key = self._get_key(corner_idx, issue_type, pre=True)
        used_idx = self.coaching_history.get(history_key, -1)
        next_idx = (used_idx + 1) % len(self.phrases[key])
        self.coaching_history[history_key] = next_idx
        
        phrase = self.phrases[key][next_idx]
        
        if complex_name:
            return phrase.format(idx=corner_idx, delta=abs(delta), 
                               value=abs(value), name=complex_name, corners=corners)
        else:
            return phrase.format(idx=corner_idx, delta=abs(delta))
    
    def generate_post(self, corner_idx, issue_type, delta=0, value=0,
                      complex_name="", corners=""):
        """Generate post-corner advice with 5 variations."""
        key = f"{issue_type}_post"
        if key not in self.phrases:
            return None
            
        history_key = self._get_key(corner_idx, issue_type, pre=False)
        used_idx = self.coaching_history.get(history_key, -1)
        next_idx = (used_idx + 1) % len(self.phrases[key])
        self.coaching_history[history_key] = next_idx
        
        phrase = self.phrases[key][next_idx]
        
        if complex_name:
            return phrase.format(idx=corner_idx, delta=abs(delta), 
                               value=abs(value), name=complex_name, corners=corners)
        else:
            return phrase.format(idx=corner_idx, delta=abs(delta))


# ═══════════════════════════════════════════════════════════════════════════
# Coaching Engine — Adaptive per-corner coaching with progressive targets
# ═══════════════════════════════════════════════════════════════════════════
